import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = (path) => readFile(new URL(path, import.meta.url), 'utf8');
const familySetup = await read('../src/components/family-setup-portal.tsx');
const dateField = await read('../src/components/date-field.tsx');
const relationPicker = await read('../src/components/relation-picker.tsx');
const firebaseService = await read('../src/services/firebase.ts');
const subscriptionPortal = await read('../src/components/subscription-access-portal.tsx');
const today = await read('../src/app/(tabs)/index.tsx');
const diary = await read('../src/app/(tabs)/diario.tsx');
const profile = await read('../src/app/(tabs)/perfil.tsx');
const orbit = await read('../src/components/routine-orbit.tsx');
const guestEntry = await read('../src/components/guest-entry-portal.tsx');
const webHtml = await read('../src/app/+html.tsx');
const register = await read('../src/app/registrar.tsx');
const rolePolicy = await read('../src/domain/family-access.ts');
const firestoreRules = await read('../../firestore.rules');

assert.ok(familySetup.indexOf('function SetupField') < familySetup.indexOf('export function FamilySetupPortal'), 'O campo deve permanecer fora do componente para não perder foco a cada letra.');
assert.ok(familySetup.includes('<DateField label="Data de nascimento"'));
assert.ok(familySetup.includes('<RelationPicker value={responsibleRelation}'));
assert.ok(familySetup.includes('keyboardShouldPersistTaps="handled"'));
assert.ok(dateField.includes('Escolha dia, mês e ano'));
assert.ok(dateField.includes('label="DIA"'));
assert.ok(dateField.includes('label="MÊS"'));
assert.ok(dateField.includes('label="ANO"'));
assert.ok(dateField.includes('Usar esta data'));
assert.ok(!dateField.includes('DateTimePicker'));
assert.ok(relationPicker.includes('Outra relação'));
assert.ok(relationPicker.includes('IDENTIDADE DO CUIDADOR'));
assert.ok(relationPicker.includes("const options = ['Pai', 'Mãe', 'Avó', 'Avô', 'Babá', 'Cuidador(a)', 'Tia', 'Tio']"));
assert.ok(!relationPicker.includes("'Mãe', 'Responsável', 'Avó'"), 'Responsável não deve aparecer como opção de relação.');
assert.ok(relationPicker.includes('legacyGenericRelations'), 'Valores antigos devem ser ocultados sem quebrar dados existentes.');

assert.ok(firebaseService.includes('const batch = writeBatch(db);'));
assert.ok(firebaseService.includes('await batch.commit();'));
assert.ok(firebaseService.includes('expectedRoutineStateMutationId'));
assert.ok(firebaseService.includes("'routine/conflict'"));
assert.ok(subscriptionPortal.includes("'Acesso encerrado'"));
assert.ok(subscriptionPortal.includes("foreground = isDark ? '#FFF9FF'"));
assert.ok(!subscriptionPortal.includes('Seu período de acesso terminou'));

assert.ok(today.includes('Como {profile.name || \'o bebê\'} está agora?'));
assert.ok(today.includes('Nenhum histórico anterior será inventado.'));
assert.ok(today.includes('Tirando uma soneca'));
assert.ok(today.includes('No sono da noite'));
assert.ok(today.includes('Começar depois'));
assert.ok(today.includes('Desde que horas está acordado?'));
assert.ok(today.includes('Quando essa soneca começou?'));
assert.ok(today.includes('currentStateStartedAt'));
assert.ok(today.includes('onValueChange'));
assert.ok(!today.includes('onChange={'));
assert.ok(!today.includes('Começar a partir de agora'));
assert.ok(today.includes('AÇÃO MUITO PRÓXIMA'));

assert.ok(register.includes('o sono precisa durar pelo menos 2 minutos'));
assert.ok(register.includes('Acordou agora e continuar'));
assert.ok(register.includes('Informar outro horário'));
assert.ok(register.includes('LINHA DO TEMPO PROTEGIDA'));
assert.ok(orbit.includes('groupRoutineMarkerEvents'));
assert.ok(orbit.includes('<Text style={styles.clusterCount}>{group.length}</Text>'));
assert.ok(orbit.includes('×{selectedCluster.length}'));
assert.ok(orbit.includes('onPress={() => setSelectedCluster(group)}'));
assert.ok(!orbit.includes('expandedClusterKey'));
assert.ok(!orbit.includes('clusterSatelliteTime'));
assert.ok(orbit.includes('formatOrbitDate'));
assert.ok(orbit.includes('formatOrbitInterval'));
assert.ok(orbit.includes('if (activeMarkerEvent) markerEvents.push(activeMarkerEvent);'));
assert.ok(orbit.includes('const containsActive = group.some(isCurrentActiveMarker);'));
assert.ok(!orbit.includes('activeCollides'), 'O marcador ativo não deve mais cobrir um agrupamento separado.');
assert.ok(orbit.includes('ações agrupadas'));
assert.ok(orbit.includes('formatRoutineActorLabel(event)'));
assert.ok(guestEntry.includes('<NinouBackground intense />'));
assert.ok(webHtml.includes('min-height:100dvh'));
assert.ok(guestEntry.includes("if (success) router.replace('/');"));

assert.ok(diary.includes('Remover este registro?'));
assert.ok(diary.includes('Remover registro'));
assert.ok(diary.includes('ALTERAÇÃO NO DIÁRIO'));
assert.ok(diary.includes('animationType="slide"'));

assert.ok(profile.includes('Responsável adicional'));
assert.ok(profile.includes('Somente visualização'));
assert.ok(profile.includes('Quem criou a família continua como responsável principal'));
assert.ok(rolePolicy.includes("return ['owner', 'admin', 'caregiver'].includes"));
assert.ok(rolePolicy.includes("if (normalized === 'viewer') return 'visualizacao'"));
assert.ok(firestoreRules.includes('"visualizacao"'));
assert.ok(firestoreRules.includes('roleCanWriteRoutine'));
const routineWriteRule = firestoreRules.match(/function roleCanWriteRoutine\(role\) \{([\s\S]*?)\n    \}/)?.[1] || '';
assert.ok(!routineWriteRule.includes('visualizacao'), 'Visualização não pode gravar a rotina.');
assert.ok(!routineWriteRule.includes('viewer'), 'Viewer não pode gravar a rotina.');

console.log('Fluxos mobile, foco dos campos, validade, exclusão e permissões validados.');
