import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const read = (path) => readFile(new URL(path, import.meta.url), 'utf8');
const firebase = await read('../src/services/firebase.ts');
const profile = await read('../src/state/profile-context.tsx');
const preferences = await read('../src/state/preferences-context.tsx');
const auth = await read('../src/state/auth-context.tsx');
const layout = await read('../src/app/(tabs)/_layout.tsx');
const orbit = await read('../src/components/routine-orbit.tsx');
const reports = await read('../src/app/relatorios.tsx');
const html = await read('../src/app/+html.tsx');
const guestEntry = await read('../src/components/guest-entry-portal.tsx');
const rootLayout = await read('../src/app/_layout.tsx');
const today = await read('../src/app/(tabs)/index.tsx');
const manifest = JSON.parse(await read('../public/manifest.webmanifest'));
const appConfig = JSON.parse(await read('../app.json'));
const packageConfig = JSON.parse(await read('../package.json'));

assert.equal(appConfig.expo.web.output, 'static');
assert.equal(packageConfig.scripts['export:web'], 'expo export --platform web --output-dir dist --clear');
assert.match(firebase, /const \[pointerSnapshot, familySnapshots\] = await Promise\.all/);
assert.match(firebase, /pointedCandidate \|\| \[\.\.\.candidates\]\.sort\(compareFamilyAccess\)/);
assert.match(firebase, /persistCanonicalFamilyPointer/);
assert.match(firebase, /member\.name \|\| member\.displayName \|\| account\.caregiverName/);
assert.match(profile, /families\/\{familyId\}\/profile\/main|fonte canônica/);
assert.match(preferences, /ninou\.universal\.preferences\.v3/);
assert.match(auth, /nextState === 'active'/);
assert.match(layout, /PremiumTabBar/);
assert.match(orbit, /groupRoutineMarkerEvents/);
assert.match(orbit, /onPress=\{\(\) => setSelectedCluster\(group\)\}/);
assert.doesNotMatch(orbit, /clusterSatelliteTime/);
assert.match(orbit, /Platform\.OS === 'web'/);
assert.match(guestEntry, /router\.replace\('\/'\)/);
assert.match(rootLayout, /useFonts\(Ionicons\.font\)/);
assert.match(rootLayout, /if \(!iconsLoaded && !iconFontError\) return null/);
assert.match(today, /PRÓXIMA TRANSIÇÃO/);
assert.match(today, /primaryActionCopyDesktop/);
assert.match(reports, /downloadWebFile/);
assert.match(reports, /Print\.printAsync/);
assert.match(reports, /Gerar PDF profissional/);
assert.match(reports, /Compartilhar resumo/);
assert.match(reports, /Baixar CSV para Excel/);
assert.doesNotMatch(reports, /Exportar JSON/);
assert.match(html, /apple-touch-icon/);
assert.match(html, /manifest\.webmanifest/);
assert.match(html, /min-height:100dvh/);
assert.equal(manifest.display, 'standalone');
assert.equal(manifest.icons[1].sizes, '512x512');
console.log('Paridade universal de dados, menus e órbita validada.');
