export function buildExportEvents(events = [], getEventConfig) {
  return [...events]
    .sort((a, b) => a.start - b.start)
    .map((event) => ({
      id: event.id,
      type: event.type,
      label: event.label || getEventConfig(event.type).title,
      title: event.label || getEventConfig(event.type).title,
      eventTime: Number.isFinite(Number(event.eventTime)) ? new Date(Number(event.eventTime)).toISOString() : new Date(event.start).toISOString(),
      start: new Date(event.start).toISOString(),
      end: new Date(event.end).toISOString(),
      durationMinutes: Math.round(Math.max(0, event.end - event.start) / 60000),
      detail: event.detail || "",
      notes: event.notes || "",
      createdAt: event.createdAt || "",
      createdByUid: event.createdByUid || "",
      createdByEmail: event.createdByEmail || "",
      createdByName: event.createdByName || "",
      createdByRelationship: event.createdByRelationship || "",
      caregiverName: event.caregiverName || "",
      caregiverRole: event.caregiverRole || event.caregiverRelationship || "",
      caregiverRelationship: event.caregiverRelationship || "",
      caregiverLabel: event.caregiverLabel || "",
      babyId: event.babyId || "",
      familyId: event.familyId || "",
      createdAtClient: event.createdAtClient || null,
      authorName: event.authorName || "",
      responsibleName: event.responsibleName || "",
      updatedAt: event.updatedAt || "",
      updatedByUid: event.updatedByUid || "",
      updatedByEmail: event.updatedByEmail || "",
      updatedByName: event.updatedByName || "",
      updatedByRelationship: event.updatedByRelationship || "",
      lastAction: event.lastAction || "",
    }));
}
